
name: Publish Release to NuGet

on:
  release:
    types: [published]

jobs:
  publish-to-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Release Build & Pack CosmosDB.Extensions.SessionTokens.AspNetCore
        run: >
         dotnet pack 
         --configuration Release 
         -p:ContinuousIntegrationBuild=true
         -p:PackageVersion=${{ github.event.release.tag_name }}
         src\CosmosDB.Extensions.SessionTokens.AspNetCore\CosmosDB.Extensions.SessionTokens.AspNetCore.csproj
      - name: Publish CosmosDB.Extensions.SessionTokens.AspNetCore to int.nugettest.org
        run: >
          dotnet nuget push 
          src\CosmosDB.Extensions.SessionTokens.AspNetCore\bin\Release\CosmosDB.Extensions.SessionTokens.AspNetCore.${{ github.event.release.tag_name }}.nupkg
          --source https://int.nugettest.org/v3/index.json
          --api-key ${{ secrets.NUGETTEST_API_KEY }}